//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_Puntuacion_Chambo.Models.DatosBD
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tbl_candidatas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_candidatas()
        {
            this.tbl_presentacion_cuatro = new HashSet<tbl_presentacion_cuatro>();
            this.tbl_presentacion_dos = new HashSet<tbl_presentacion_dos>();
            this.tbl_presentacion_tres = new HashSet<tbl_presentacion_tres>();
            this.tbl_presentacion_uno = new HashSet<tbl_presentacion_uno>();
        }
    
        public int id { get; set; }
        [Required(ErrorMessage = "Por Favor Ingresa Nombres Validos")]
        public string nombres { get; set; }

        [Required(ErrorMessage = "Por Favor Ingresa Apellidos Validos")]
        public string apellidos { get; set; }
        public byte[] imagen { get; set; }
        public string respresentacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_presentacion_cuatro> tbl_presentacion_cuatro { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_presentacion_dos> tbl_presentacion_dos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_presentacion_tres> tbl_presentacion_tres { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_presentacion_uno> tbl_presentacion_uno { get; set; }
    }
}
