//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sistema_Puntuacion_Chambo.Models.DatosBD
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tbl_presentacion_uno
    {
        public int id { get; set; }
        public Nullable<int> fk_candidatas_id { get; set; }
        public Nullable<int> fk_users_id { get; set; }
        [Required(ErrorMessage = "Campo Obligatorio")]
        [Range(0, 4, ErrorMessage = "Valores permitidos Entre 0 y 4")]
        public Nullable<byte> nota1 { get; set; }
        [Required(ErrorMessage = "Campo Obligatorio")]
        [Range(0, 2, ErrorMessage = "Valores permitidos Entre 0 y ")]
        public Nullable<byte> nota2 { get; set; }
        [Required(ErrorMessage = "Campo Obligatorio")]
        [Range(0, 2, ErrorMessage = "Valores permitidos Entre 0 y 2")]
        public Nullable<byte> nota3 { get; set; }
    
        public virtual tbl_candidatas tbl_candidatas { get; set; }
        public virtual tbl_users_jueces tbl_users_jueces { get; set; }
    }
}
